voteapp/stats/views.py
import sys
from flask import Flask, Blueprint, request, render_template, redirect, url_for, flash, abort
from voteapp import db
from voteapp.models import Member, load_user
from flask_login import login_user, login_required, logout_user, current_user
'''
============================================================
                        STATS
============================================================
'''
'''
    sqlalchemy.engine.result.ResultProxy
    sqlalchemy.engine.result.RowProxy
    The keys and the values need to be in lists passed in separately.
'''
stats_blueprint = Blueprint('stats',
                              __name__,
                              template_folder='templates/stats', static_folder='static')

@stats_blueprint.route('/stats')
@login_required
def stats():
    data = []
    label = []
    sql = '''select members.name, members.id, count(*) AS "total"
    from members join votes on members.name = votes.userName
    group by members.name
    ORDER BY total desc'''
    resultList = db.engine.execute(sql)
    rows = resultList.fetchall()
    for i in rows:
        label.append(str(i[0]))
        data.append(i[2])
        print("data: ", data, file=sys.stderr)
    return render_template('stats.html', results = rows, label = label, data = data)

@stats_blueprint.route('/stats/<int:memberId>')
@login_required
def countVotes(memberId):
    data = []
    label = []
    sql = '''select showName, count(*) as "total"
    from votes
    where memberId = ?
    group by showName
    order by total desc, showName
    '''
    resultList = db.engine.execute(sql, (memberId,))
    rows = resultList.fetchall()
    for i in rows:
        label.append(str(i[0]))
        data.append(i[1])
        print("data: ", data, file=sys.stderr)
    print("resultList: ", type(resultList), file=sys.stderr)
    member = load_user(memberId)
    return render_template('showlist.html', member = member, results = rows, label = label, data = data)

voteapp/stats/templates/stats/showlist.html
{% extends "base-back.html"%}
{% block content %}


  <!-- HEADER -->
  <header id="main-header" class="py-2 bg-primary text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>
            <i class="fas fa-cog"></i>Voting Stats</h1>
        </div>
      </div>
    </div>
  </header>

  <!-- Results -->
  <section id="results">
    <div class="container">
      <div class="row">

        <div class="col-md-4">
          <div class="card">
            <div class="card-header">
              <h4>{{member.name|capitalize}}'s Vote List</h4>
            </div>
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th>Show</th>
                  <th>Total Votes</th>
                </tr>
              </thead>
              <tbody>
              <!-- if resultList null, print "No Votes Found" -->
                {%for item in results %}
                    <tr>
                        <td>{{item.showName}}</td>
                        <td>{{item.total}}</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div> <!-- end card -->
        </div> <!-- end col -->

        <div class="col-md-8">
          <!-- Start graph-->
          <div class="wrapper p-3" style="border:1px solid #000000">
            <h1 class="display-4">{{member.name|capitalize}}'s Distribution</h1>
            <canvas id="bar-chart" width="800" height="450"></canvas>
          </div>

          <script type="text/javascript">
            new Chart(document.getElementById("bar-chart"), {
                type: 'bar',
                data: {
                  labels: {{label|safe}},
                  datasets: [{
                    label: "Vote Distribution",
                    backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","#f4d03f","#000066"],
                    data: {{data}}
                  }]
                },
                options: {
                  title: {
                    display: true,
                    text: 'Vote Distribution'
                  }
                }
            });
          </script>
        </div> <!-- end col -->

        </div>
      </div>
    </div>
  </section>


  {% endblock %}

voteapp/stats/templates/stats/stats.html
{% extends "base-back.html"%}
{% block content %}


  <!-- HEADER -->
  <header id="main-header" class="py-2 bg-primary text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>
            <i class="fas fa-cog"></i>Voting Stats</h1>
        </div>
      </div>
    </div>
  </header>

  <!-- Results -->
  <section id="results">
    <div class="container">
      <div class="row">



        <div class="col-md-4">
          <div class="card">
            <div class="card-header">
              <h4>Top Voting Participants</h4>
            </div>

            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th>User Name</th>
                  <th>Total Votes</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {%for item in results %}
                  <tr>
                    <td>{{item.name|capitalize}}</td>
                    <td>{{item.total}}</td>
                    <td><a class="btn btn-primary btn-sm" href="{{url_for('stats.countVotes', memberId = item.id)}}"
                      role="button"> <i class="fas fa-info"></i>&nbsp; Details</a></td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div> <!-- end card -->
        </div> <!-- end col -->

        <div class="col-md-8">

          <!-- Start graph-->
          <div class="wrapper p-3" style="border:1px solid #000000">
            <h1 class="display-4">Votes by Person</h1>
            <canvas id="polar-chart" width="800" height="450"></canvas>
          </div>

          <script type="text/javascript">
            new Chart(document.getElementById("polar-chart"), {
                type: 'polarArea',
                data: {
                  labels: {{label|safe}},
                  datasets: [{
                    label: "Vote Distribution",
                    backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","#f4d03f","#000066"],
                    data: {{data}}
                  }]
                },
                options: {
                  title: {
                    display: true,
                    text: 'Vote Distribution'
                  }
                }
            });
          </script>


        </div> <!-- end col -->




      </div> <!-- end row -->

      </div>
    </div>
  </section>


  {% endblock %}